---
title: "SDS 237 - Mini-Project: Interview"
author: "Xinxin Zhang"
date: "Last updated on `r Sys.Date()`"
output: pdf_document
bibliography: interview.bib
csl: ../../resources/chicago-author-date.csl
---

> Compose your write-up below.

If we think about what constructs our world today,  it seems like anything related to data is a mainstream culture. Besides the majority of professionals and scientists who perform the highly science-based data technical work, humanities inevitably comes to merge with data as well. Here it's called digital humanities. Digital scholarship is the broad umbrella of digital humanities, which is defined as "…the use of digital evidence, methods of inquiry, research, publication and preservation to achieve scholarly and research goals."[@inproceedings] In the increasingly tendency of multi-disciplinary intersection at the higher education institute, I'm hereby interested in investigate the question: what investments do data professionals bring in their work in the field of data scholarship?
 
To understand it better, I conducted interviews with two data professionals who work at Smith College libraries. The first interviewee is Jean Ferguson, who is Director of Learning, Research, and Technology. The second interviewee is EJ(due to confidentiality reasons, the interviewee will be referred as EJ in this essay), who is a Metadata Technologies Librarian, which is part of the big umbrella of digital scholarship. I conducted these two interviews on October 31st and November 2nd, both in the library setting.
 
EJ had a business degree with a focus on computer science in their undergraduate, with a minor in anthropology. He had been working in insurance and non-profit companies, and eventually fell into the library roles. He pursued a master in library sciences and spent eight and half years in Harvard university doing cataloging jobs, then he came to Smith College. Jean had worked in the information technology company, started by training people how to use technology, and she always worked with technology related people. Prior to joining Smith, Jean was the librarian and project lead at the University of California, Berkeley Library and the Head of Research and Instruction Services at Duke University Libraries. It might not be hard to notice that both of them were previously working in the corporate environment as tech people, and made the decision to become technology related librarians. EJ said "in the corporate environment, I couldn't get around by drawing a large amount of money out of people related to their health. I want to do somethings that's sustainable, and I could find moral goods in the world." Jean thought it was just natural for me to work in business after graduation because that's what my parents do. However, she explained the reason for making the turning point as, "in business, I was helping the company earn money. In here, I feel like I'm helping to develop minds." Obviously, the reason why they share a similar transition of career trajectory is that they both want to pursue careers that have higher meaning to their individual lives and to the society, rather than simply earning money.
 
Surprisingly, they also share a similar motivation to get involved with digital scholarship works. "I learn a lot about different things. I learn them but am not an expert in it. It allows me to have a broad interest," answered by EJ. Cataloger, system librarian, and data hygienist are the three names that he defines himself throughout the whole interview, which is corresponding to what he said he loves to learn knowledge likely but not becomes the expert in it. Jean loves it is always cross-disciplinary or gets involved with two or more fields. It's "…a different way of thinking something, even if it's old." They both enjoy the cross-disciplinary element of digital scholarship, and appreciated it as the opportunity to learn more fields. When the meaning breaks down into details, their sources of pleasure become a little bit different. EJ likes to have interesting intellectual problems to solve everyday. After researching and solving the puzzle, he can move to something new, so it keeps his job exciting. He describes himself as the person who loves "…looking under the rock." He was once working on a project that 35,000 titles are there in the library, but librarians just can't find them in the catalog. The moment he and his colleagues found it out, he felt a sense of accomplishment. On the other hand, Jean has a particular passion in data visualization. "I really like analyzing data and bringing it to clean data. … Seems too hard to decipher and create a picture about it. Someone who doesn't know much about it can really understand." So, as she describes, Jean put the emphasis on using data as a communication tool, to let other people who are not in the field be able to understand it.
 
Technology is the big component of working in the digital scholarship, other than the domain knowledge of library sciences. It seems like both EJ and Jean have their approach to it. Jean is more like a manager role, so she always work with technology people, as she said that "I can't do programming language at all, but I always reach out to people who can do.'' We can see that as the director, she draws on other data professional's skills to offset her own weaknesses. It is built on the good connection of people and a strong sense of making collaboration in the community. On the other hand, for EJ, besides his free time both in Harvard and Smith, he does professional development of data science training for librarians. He learned R and pythons, and communicated with professionals coming in. He will be able to TA in future years. So, one is highly based on people around her, probably due to her managing roles; another one is trained by gaining skills himself, by investing extra time when he is free.
 
When it comes to the question of what is special to them to work in the library setting, what brings to Jean is that the sense of community and values. There are few different places on campus that work with digital scholarship, like classroom projects, museum visits, image center, etc. She emphasizes it by saying that "being in a small school and having different places that you can work with, people are always very happy to … work with you. I like connecting across campus." Again, that sense of belongingness in the community landed her in her pursuit, and working in the small liberal arts college like Smith satisfies her needs like that. On the other hand, EJ doesn't have that mental need to have belongingness, it's more about what he does. He was surprised to find out that Smith made an investment in me and my colleague's time to work on a four and half year project of doing behind scene Catalog work. As said, he appreciates and respects the value of education, and investment in building library resources and hiring relatively more staff in libraries. However, compared to Jean who enjoys working with students and alumnae by immersing herself in the education setting, EJ thinks that "I would be happy to work in other fields as well just like having deep knowledge of particular fields, having it working different types of works. It just happens that cataloging and metadata meet that interest."
 
By reviewing EJ and Jean's answers, they share a lot of similarity to work in the field of digital scholarship: they both worked in corporate environments before and made the decision to transit into library works by holding a master in library sciences. They all appreciate having the human perspective and social component in doing technology work, and made the investment by either working with technology professionals or training in the extra time. Jean clearly knows she would enjoy working in the library in the academic setting since she loves to "develop minds". EJ thinks his interests and skills would be more applicable to other fields as well as long as they require deep domain knowledge. Therefore, it is clear that   people working in the digital scholarship nowadays may come from different fields originally, and made the decision to turn into work of digital scholarship by investing extra time in training themselves in technology and degree. That adds the element of having multiple perspectives of doing work, especially human and social components, with a higher pursuit of finding meaning in careers, rather than purely focusing on technology and earning money for corporations. 


