---
title: "SDS 237 - Mini-Project: Infrastructural Analysis Timeline"
author: "Xinxin Zhang"
date: "Last updated on `r Sys.Date()`"
output: pdf_document
bibliography: infrastructural-analysis.bib
csl: ../../resources/chicago-author-date.csl
---

> Complete your timeline entries below, including a date, a description of the event, a description of the stakeholder groups at the table, and a consideration of the impact on the infrastructure's master narrative.

| Date | Description Event | Relevant Links | Description of Stakeholder Groups Involved | How did this event shape the infrastructure's master narrative? |
|------|-------------------|----------------|--------------------------------------------|-----------------------------------------------------------------|
| 1972 | the Intergovernmental Conference on Cultural Policies in Europe, Helsinki, 1972 (UNESCO 1972a) The main question was: How could scientific research contribute to a better cultural development? | https://doi.org/10.18261/ISSN2000-8325-2019-01-10 | European Member states. | It was being asked the task of governments to define cultural policy, not researchers.|
| 1986 | The UNESCO framework for cultural statistics. The 1986 FCS had a significant first step for building a framework for cultural statistics.| https://link.springer.com/referenceworkentry/10.1007/978-94-007-0753-5_3079 | Statistical commission and economic commission for Europe |The framework was developed by UNESCO member states who were largely from Europe, which is a developed and white-dominant region.|
| 2009 | University of Leeds did a impact case study: Calvin Taylor's (Professor in Cultural Economy, University of Leeds) and Pratt together with Burns Owen Partnership (BOP), a consultancy specialising in cultural statistics, were subsequently commissioned by UNESCO to review the 1986 Framework and the team submitted its `Expert Scoping Study' offering specific recommendations for its revision in 2005. |https://impact.ref.ac.uk/casestudies/CaseStudy.aspx?Id=6398|Burns Owen Partnership (BOP), and Professor Taylor and Pratt | The core of the recommendations for the UNESCO Framework consists of three elements: cultural domains, the culture cycle and a suite of indicators.|
| 2009 | 2009 UNESCO Framework for Cultural Statistics. A revised version based on the 1986 Framework for Cultural Statistics | https://purl.org/spc/digilib/doc/vayzx | A collaborative effort by the UNESCO Institute for Statistics (UIS) and the UNESCO Culture Sector | The revised framework reflected a more inclusive approach and the priorities of developing countries, not just the white-dominant developed European countries |
| 2012 | Cultural Statistics in Africa: The Missing Link. There were challenges in accessing and using cultural data in African Union member states and suggests the development of cultural indicators and capacity building in cultural statistics to improve data collection, quality, and availability in Africa. |https://uis.unesco.org/sites/default/files/documents/cultural-statistics-in-africa-the-missing-link-culture-2012-en_0.pdf| 3rd Pan-African Cultural Congress (PACC3) | It was a called request from a developing regions to improve the 2009 Cultural Framework, which intended to be more inclusive but it seemed like it had a long way to go.|
|2012|  Mapping the Trade in the Creative Industries. Key cultural policy areas in the Caribbean region were identified such as intangible cultural heritage, festivals and cultural diversity. This issue was reflected into policy as a result of the COTED meeting in April 2011, where it was agreed that the region needs to improve the availability of statistics from the creative economy in the Caribbean.| https://uis.unesco.org/sites/default/files/documents/mapping-the-trade-in-the-creative-industries-2012-en.pdf |United Nations Educational Scientific and Cultural Organisation. | Like the African missing link, this published volume was also a called request to consider more accessibility of developed areas such as Caribbean region.|
|2012|Update the definition of the cultural field, to create a new framework for this field that would be compatible with the framework that UNESCO adopted
in 2009, while reflecting on recent phenomena on creativity and the development of creative industries, on the measurement of new cultural habits and practices, and on the transformations in the cultural economy due to digitisation.| https://ec.europa.eu/assets/eac/culture/library/reports/ess-net-report_en.pdf|ESSnet-Culture project co-financed by the European Commission. Ministries of Culture, from National Statistical Offices and the European Commission.| ESSnet-Culture prepared the
ground for a production of European statistics on the culture.|
|2015|The report indicated that seven training workshops attended by 247 people were held from 2007 to 2013, with more being planned, particularly for the regions of Latin America and the Arab States.|https://uis.unesco.org/sites/default/files/documents/a-case-study-of-serbia-measuring-the-economic-contribution-of-cultural-industries-handbook-4-2015-en.pdf|Regions of Latin America and Arab States. This report was prepared by Ms Hristina Mikić, Modern Business School, Belgrade/Creative Economy Group.|This report indicates that the framework had a significant impact on improving accessibility to cultural statistics of Latin American and Arab.|
|2019|This fourth edition of publication Culture statistics — 2019 edition presents a selection of indicators on culture pertaining to cultural employment, international trade in cultural goods, cultural enterprises, cultural participation and the use of the internet for cultural purposes, as well as household and government cultural expenditure.|https://ec.europa.eu/eurostat/documents/3217494/10177894/KS-01-19-712-EN-N.pdf/915f828b-daae-1cca-ba54-a87e90d6b68b|Eurostat. European Union (EU) and its Member States. European Free Trade Area (EFTA).|Made methodological recommendations to define and delineate the cultural sphere of influence taking account of various European/international statistical classifications. For example, within the domain of cultural employment the network proposed to develop a new methodological approach to estimate cultural employment.|
|2022|The report by WP4 will present the mapping of roles and dynamics of internal and external
stakeholders in Cultural Heritage (CH) and implication to education and training systems.|https://charter-alliance.eu/wp-content/uploads/2022/10/D4.1-Report-Who-is-not-a-stakeholder-in-cultural-heritage-_V2.pdf|European Commission|Based on culture-cycle defined in 2009 UNESCO framework for cultural statistics, CHARTER has refined a model to describe cultural heritage that considers the heritage practices and social engagement in a generic and circular way.|
