---
title: "SDS 237 - Mini-Project: Infrastructural Analysis"
author: "Xinxin Zhang"
date: "Last updated on `r Sys.Date()`"
output: pdf_document
bibliography: infrastructural-analysis.bib
csl: ../../resources/chicago-author-date.csl
---

In 2009, the constitution of the United Nations Educational, Scientific and Cultural Organization (UNESCO) republished the Framework for Cultural Statistics, a revised version based on the 1986 Framework for Cultural Statistics. UNESCO was born in London in 1945, which is less than thirty years after two World Wars, with a clear vision to "bring people together and strengthen the intellectual and moral solidarity of humankind, through mutual understanding and dialogue between cultures," as stated in UNESCO's official website. The 2009 UNESCO Framework for Cultural Statistics (FCS) is the infrastructure to measure and evaluate the impacts of world-wide culture using cultural statistics methodology, and it was republished considering the new appearance of technology and how it has influenced the way people access culture including intangible heritage, and evolving cultural practices and policies. In this essay, by studying its established history and updates after publication by different stakeholder groups, it is evident that the framework aimed to take into account cultural globalization and technology emergence. However, there is a tendency for this cultural statistical infrastructure to remain quite Europe-centric, making it more accessible to developed countries.

In the framework, the statistical definition of culture is based on cultural domains, which are defined as "a domain that includes all related activities, whether economic or social"(2009, UNESCO). These cultural domains are categorized by the number of industries, including:

      A: Cultural and Natural Heritage
      B: Performance and Celebration
      C: Visual Arts and Crafts
      D: Books and Press
      E: Audio-visual and Interactive Media
      F: Design and Creative Services
      Intangible Cultural Heritage (transversal domain)

This cultural classification system aims to capture the full range of cultural expression. However, while the framework successfully quantifies the abstract concept of culture into countable industries, it naturally excludes the uncountable, undocumented, and informal aspects of culture. Any infrastructure is supposed to play a relational function, like building a communication bridge between the constructor and the users. But this 2009 FCS speaks from a singular voice, assuming white-dominated group can speak for everyone world-wide. As stated in the new approach section, "if cultural production takes place within the informal economy or non-monetary realm, it may be estimated" (2009, UNESCO). It is undeniable that the tangible monetary aspect serves as the benchmark here, and what classifies an industry within cultural domains is its economic measurement. Developed regions like North America and Europe have more resources to invest in and run cultural industries compared to less developed regions like Africa, Latin America, Asia, and the Caribbean. Keeping this in mind, the 2009 UNESCO cultural statistical framework is generally more applicable to developed countries around the world. Again, this accessibility and applicability of using this framework demonstrate the singular voice that white-dominated member groups speak for other countries in the world .

Tracing back to 1972, the Intergovernmental Conference on Cultural Policies in Helsinki, Europe, first raised the question of how scientific research could contribute to better cultural development (Vestheim, 2019). This laid the foundation for UNESCO's first cultural statistics framework in 1986 (Sung, 2014). This framework was developed by the Statistical Commission and Economic Commission for Europe, with UNESCO member states largely from Europe, a developed and historically white-dominant region. Professor Taylor from the University of Leeds in the UK made the core recommendations for the 2009 UNESCO Framework, and it's worth noting that the UK was part of the European Union and a developed country.

After the publication of the official framework in 2009, there were continuous requests from less developed regions for improvements. In 2012, it was indicated that there were "challenges in accessing and using cultural data in African Union member states" (Pessoa & Ababa, 2012). In the same year, the Caribbean region requested improvements in the availability of statistics from the creative economy in Caribbean Creatives Volume 1 Issue 4. 

Unlike less developed countries that were still striving to gain more access to statistics, developed regions like Europe were already updating the UNESCO statistical cultural framework and developing their own cultural statistical framework. In 2012, due to the new phenomenon of digitization in creative industries, Ministries of Culture from National Statistical Offices and the European Commission started the ESSnet Culture project to "update the definition of the cultural field and create a new framework." They also designed measurements for new cultural habits and practices due to digitization of the cultural economy, with a more rigid definition of cultural domains than UNESCO's. Because developed regions like Europe adopted new technology faster in people's daily lives, they entered the digital society faster than less developed regions. 

This change in definition favored the culture industries in the euro-centric western world, making cultural participation in Europe more convenient to count and record but leaving less-developed countries behind. In 2019, Eurostat, the European Union (EU), and its Member States published the fourth edition of Cultural Statistics and made methodological recommendations to define and delineate the cultural sphere of influence, taking into account various European and international statistical classifications. For example, within the domain of cultural employment, the network proposed to develop a new methodological approach to estimate cultural employment (European Union, 2019). In 2022, the report by WP4 and the European Commission stated that, based on the culture-cycle defined in the 2009 UNESCO framework for cultural statistics, "CHARTER has refined a model to describe cultural heritage that considers the heritage practices and social engagement in a generic and circular way" (WP4, 2022). Both updates from Eurostat and WP4 have contributed to the development and refinement of cultural statistics definitions and measurements suitable for European countries.

While less-developed countries worked hard to adopt the framework and keep up with the rapidly changing world, it's important to note that the 2009 UNESCO Framework for Cultural Statistics originated from discussions in the 1972 conference in Helsinki, Europe. The history of UNESCO might have also influenced its development, as UNESCO was established in the UK and its headquarters are in France. With this in mind, it's not surprising that European countries made progress in updating the 2009 framework. However, it should be acknowledged that European member states may have a bias and may not fully understand the cultural situations and experiences in less developed countries or in other parts of the non-Western world, resulting in an euro-centric cultural statistics infrastructure.

